#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all test clean

# 1. The default target: ensures .build exists, runs cmake, then builds
all:
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR)
	@make -C $(BUILD_DIR) --no-print-directory

# 2. Run your tests
test:
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DENABLE_TESTS=ON
	@cmake --build $(BUILD_DIR) --target cortex_test
	@./cortex_test

# 3. Clean up only the build artifacts
purge:
	@rm -rf $(BUILD_DIR)
	@rm -f cortex cortex_test

clean:
	@make purge
	@make all --no-print-directory
